In [2]:
import numpy as np

random_gen(num_rounds)

In [153]:
def random_gen(num_rounds):
    dice_rolls_arr = np.zeros(6)
    outcome = np.random.randint(6, size=(2,num_rounds)) +1
    return(outcome)
random_gen(10)

array([[3, 6, 2, 3, 2, 2, 5, 4, 6, 6],
       [5, 3, 1, 4, 5, 4, 3, 6, 6, 1]])

calc_conditional(dice_rolls_arr, main_event, given_event)

In [152]:
def calc_conditional(dice_rolls_arr, main_event, given_event):
    num_rounds = 1
    dice_rolls_arr = np.zeros(6)
    for round in range(num_rounds):
        outcome = np.random.randint(6, size=(2, 10)) +1
        dice_rolls_arr[outcome[0] - 1] += 1
        dice_rolls_arr[outcome[1] - 1] += 1
        print('Round', round + 1, ': \n ', outcome)
    print(dice_rolls_arr)
    num_main_given_event = 0.0277    
    num_given_event = dice_rolls_arr[given_event - 1]
    p_given_event = num_given_event / num_rounds
    p_main_given_event = num_main_given_event / p_given_event
    print('conditional probability is:' , p_main_given_event)
    
    
calc_conditional('dice_rolls_arr', 6, 5)

Round 1 : 
  [[4 4 3 5 4 5 1 3 2 2]
 [1 4 3 1 2 4 2 1 5 3]]
[2. 2. 2. 2. 2. 0.]
conditional probability is: 0.01385


calc_joint(dice_rolls_arr, main_event, given_event):

In [193]:
def calc_joint(dice_rolls_arr, main_event, given_event):
    num_rounds = 1
    dice_rolls_arr = np.zeros(6)
    for round in range(num_rounds):
        outcome = np.random.randint(6, size=(2, 10)) +1
        dice_rolls_arr[outcome[0] - 1] += 1
        dice_rolls_arr[outcome[1] - 1] += 1
        print('Round', round + 1, ': \n ', outcome)
    num_main_given_event = 0.0277    
    num_given_event = dice_rolls_arr[given_event-1]
    p_given_event = num_given_event / num_rounds
    p_main_given_event = num_main_given_event / p_given_event
    p_joint = p_given_event * p_main_given_event
    print('joint probability is :', p_joint)
    
calc_joint('dice_rolls_arr', 1, 5)

Round 1 : 
  [[5 4 3 4 3 6 3 2 1 2]
 [2 4 1 2 4 5 5 1 5 5]]
joint probability is : 0.0277


test(num_rounds, dice_rolls_arr, main_event, given_event)

In [199]:
def test(dice_rolls_arr, main_event, given_event):
    num_rounds = 1
    dice_rolls_arr = np.zeros(6)
    for round in range(num_rounds):
        outcome = np.random.randint(6, size=(2, 10)) +1
        dice_rolls_arr[outcome[0] - 1] += 1
        dice_rolls_arr[outcome[1] - 1] += 1
        print('Round', round + 1, ': \n ', outcome)
    num_main_given_event = 0.0277    
    num_given_event = dice_rolls_arr[given_event-1]
    p_given_event = num_given_event / num_rounds
    p_main_given_event = num_main_given_event / p_given_event
    print('conditional probability is:' , p_main_given_event)
    p_joint = p_given_event * p_main_given_event
    print('joint probability is :', p_joint)
    
test('dice_rolls_arr', 4, 6)

Round 1 : 
  [[4 2 6 2 1 2 1 1 5 6]
 [4 3 1 5 1 1 2 2 4 1]]
conditional probability is: 0.0277
joint probability is : 0.0277
